### ISSUE TITLE
Consider best practices around keychain items persisting app installs

### ISSUE THREAD

**Issue by tylermilner** [BottleRocketStudios/iOS-SessionTools#10]
Since keychain items persist app installs, you typically have to do one of 3 things to ensure that you're not using keychain data from a previous installation of the app:
- Detect and remove any existing keychain items upon first app launch.
- Entangle a unique installation identifier with the keychain name (as suggested on the [Apple forums](https://forums.developer.apple.com/thread/36442#thread-message-112814)).
- Implement custom logic to avoid using stale/previous keychain items until the user has authenticated.

I feel like we should at least provide some documentation/guidance around this scenario, if not building it into SessionTools directly. The current project that I'm on didn't take this into account so technically keychain items are persisting app installs, which makes it absolutely critical that the authentication status be checked before sending off authenticated API requests, otherwise you'll be using an access token from a previous app installation (and potentially different user).

**Comment by ganttastic** [comment]
@tylermilner, 

What's your preferred option? I was thinking we keep the current implementation and add documentation. There could be some cases where a developer might want to keep that keychain item around. As you said above, a dev can always append an install ID to the keychain key when setting up the Session object.

**Comment by tylermilner** [comment]
@ganttastic Yeah, I definitely think some documentation is in order. I was thinking that it might also be nice to take a stance and build it into SessionTools directly (with the flexibility to use an alternate approach) so that every project doesn't end up needing to write the same boilerplate code. This assumes that we might already have a common way of doing this across projects already (or maybe we get together and decide how we want to do it going forward).

**Comment by ganttastic** [comment]
Completed with [PR #17](https://github.com/BottleRocketStudios/iOS-SessionTools/pull/16)
